name: solar
description: Solar for mobile.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  webview_flutter: ^4.7.0
  webview_flutter_android: ^4.3.0
  webview_flutter_wkwebview: ^3.17.0
  flutter_svg: ^2.0.9
  http: ^1.1.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.4
  path_provider: ^2.1.5
  permission_handler: ^11.0.1
  open_file: ^3.5.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.2
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
